[project]
name = "fastapi-hey-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.136.1",
    "mkdocstrings-python>=2.0.3",
    "pydantic-settings>=2.14.0",
    "zensical>=0.0.38",
]

[dependency-groups]
dev = [
    "pytest>=8.0.0",
    "httpx>=0.27.0",
]

[tool.uv.sources]
fastapi-hey-api = { workspace = true }

[tool.setuptools.packages.find]
where = ["."]
include = ["fastapi_hey_api*"]
